import { useEffect, useMemo, useState } from "react";
import type {
  DailyReport,
  PersistedReportRef,
  WeeklyReport,
} from "@desktop-tracker/shared";
import { api } from "../lib/api";
import { ScoreCard } from "../components/ScoreCard";
import { BreakdownList } from "../components/BreakdownList";
import { StormList } from "../components/StormList";
import { HealthBars } from "../components/HealthBars";
import { ExportMenu } from "../components/ExportMenu";
import { AiReviewCard } from "../components/AiReviewCard";
import { formatDuration } from "../lib/format";

function isDaily(p: DailyReport | WeeklyReport): p is DailyReport {
  return (p as DailyReport).date !== undefined;
}

function formatDate(ts: number): string {
  return new Date(ts).toLocaleDateString(undefined, {
    weekday: "short",
    month: "short",
    day: "numeric",
    year: "numeric",
  });
}

export function Reports() {
  const [filter, setFilter] = useState<"all" | "daily" | "weekly">("all");
  const [refs, setRefs] = useState<PersistedReportRef[]>([]);
  const [selectedId, setSelectedId] = useState<number | null>(null);
  const [payload, setPayload] = useState<DailyReport | WeeklyReport | null>(null);
  const [loadingPayload, setLoadingPayload] = useState(false);

  useEffect(() => {
    let cancelled = false;
    const kind = filter === "all" ? undefined : filter;
    api.reportsHistory(kind, 100).then((list) => {
      if (cancelled) return;
      setRefs(list);
      if (list.length > 0 && (selectedId === null || !list.some((r) => r.id === selectedId))) {
        setSelectedId(list[0]!.id);
      } else if (list.length === 0) {
        setSelectedId(null);
        setPayload(null);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [filter]);

  useEffect(() => {
    if (selectedId === null) {
      setPayload(null);
      return;
    }
    let cancelled = false;
    setLoadingPayload(true);
    api.reportPayload(selectedId).then((p) => {
      if (!cancelled) {
        setPayload(p);
        setLoadingPayload(false);
      }
    });
    return () => {
      cancelled = true;
    };
  }, [selectedId]);

  const selectedRef = useMemo(
    () => refs.find((r) => r.id === selectedId) ?? null,
    [refs, selectedId]
  );

  return (
    <div className="p-8 space-y-6 max-w-[1400px]">
      <header className="flex items-baseline justify-between">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Reports history</h1>
          <p className="text-sm text-subtle mt-1">
            Persisted reports auto-generated by the scheduler.
          </p>
        </div>
        <div className="flex items-center gap-2 text-sm" data-export-chrome>
          {(["all", "daily", "weekly"] as const).map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={
                "px-3 py-1.5 rounded-md border transition-colors " +
                (filter === f
                  ? "border-accent/50 bg-accent/10 text-accent"
                  : "border-border hover:bg-elevate")
              }
            >
              {f === "all" ? "All" : f === "daily" ? "Daily" : "Weekly"}
            </button>
          ))}
        </div>
      </header>

      <div className="grid grid-cols-12 gap-6">
        <aside className="col-span-4 rounded-xl border border-border bg-surface/40">
          <div className="px-4 py-3 border-b border-border text-sm font-medium text-text flex justify-between">
            <span>Saved reports</span>
            <span className="text-subtle">{refs.length}</span>
          </div>
          <div className="divide-y divide-slate-800/60 max-h-[70vh] overflow-y-auto">
            {refs.length === 0 && (
              <div className="px-4 py-6 text-sm text-subtle">
                No saved reports yet — they'll appear here after the daily (23:55)
                or weekly (Sun 21:00) run.
              </div>
            )}
            {refs.map((r) => (
              <button
                key={r.id}
                onClick={() => setSelectedId(r.id)}
                className={
                  "w-full text-left px-4 py-3 hover:bg-elevate/60 transition-colors " +
                  (selectedId === r.id ? "bg-elevate/70" : "")
                }
              >
                <div className="text-sm text-text">{formatDate(r.periodStart)}</div>
                <div className="text-xs text-subtle mt-0.5 flex justify-between">
                  <span>{r.kind === "daily" ? "Daily report" : "Weekly report"}</span>
                  <span className="tabular-nums">
                    {new Date(r.createdAt).toLocaleString(undefined, {
                      month: "short",
                      day: "numeric",
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </span>
                </div>
              </button>
            ))}
          </div>
        </aside>

        <section className="col-span-8 space-y-4">
          {loadingPayload && (
            <div className="text-sm text-subtle">Loading report…</div>
          )}
          {!loadingPayload && payload && selectedRef && (
            <PersistedReportView
              ref_={selectedRef}
              report={payload}
            />
          )}
          {!loadingPayload && !payload && selectedRef && (
            <div className="text-sm text-subtle">
              Report payload could not be parsed.
            </div>
          )}
        </section>
      </div>
    </div>
  );
}

function PersistedReportView({
  ref_,
  report,
}: {
  ref_: PersistedReportRef;
  report: DailyReport | WeeklyReport;
}) {
  const daily = isDaily(report);
  const baseName = daily
    ? `daily-${report.date}`
    : `weekly-${(report as WeeklyReport).weekStart}`;
  return (
    <>
      <div className="flex items-baseline justify-between">
        <h2 className="text-xl font-semibold tracking-tight">
          {daily ? "Daily" : "Weekly"} · {formatDate(ref_.periodStart)}
        </h2>
        <ExportMenu baseName={baseName} />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <ScoreCard
          label="Productivity"
          value={daily ? report.productivityScore : (report as WeeklyReport).averageProductivityScore}
          delta={daily ? undefined : (report as WeeklyReport).productivityScoreDelta}
          sub={report.productivityTip ?? "Steady period."}
        />
        <ScoreCard
          label="Focus"
          value={daily ? report.focusScore : (report as WeeklyReport).averageFocusScore}
          delta={daily ? undefined : (report as WeeklyReport).focusScoreDelta}
          sub={
            daily
              ? report.focusTip
              : (report as WeeklyReport).focusTip
          }
        />
        <div className="rounded-xl border border-border bg-surface/40 p-5">
          <div className="text-xs uppercase tracking-wider text-subtle">
            Active time
          </div>
          <div className="mt-2 text-4xl font-semibold tabular-nums">
            {formatDuration(report.totalActiveMs)}
          </div>
          <div className="mt-1 text-sm text-muted">
            {formatDuration(report.totalIdleMs)} idle / locked
          </div>
        </div>
      </div>

      <AiReviewCard
        review={report.aiReview}
        period={daily ? "daily" : "weekly"}
        generatable={false}
      />

      <HealthBars
        title={daily ? "Health by category — that day" : "Health by category — that week"}
        health={report.health ?? []}
        period={daily ? "day" : "week"}
      />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <BreakdownList title="By category" buckets={report.breakdown.byCategory} />
        <BreakdownList title="By app" buckets={report.breakdown.byApp} />
        <BreakdownList title="By project" buckets={report.breakdown.byProject} />
        <BreakdownList title="By website" buckets={report.breakdown.byDomain} />
      </div>

      <StormList storms={report.storms ?? []} />
    </>
  );
}
